version: '3.1'

services:
  app:
    image: authentication
    ports: 
      - 8080:80
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    ports: 
      - 3306:3306
      - 33060:33060
    